addons:
  apt: {packages: null}
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: e0867a9b-9d25-4f8e-9a87-77b02dea6c90
after_success: ['mvn cobertura:cobertura coveralls:report']
install: mvn compile org.apache.maven.plugins:maven-dependency-plugin:2.10:go-offline
  --batch-mode --show-version
jdk: [openjdk6]
language: java
script: ['export PATH="bin:$PATH"', mvn clean verify --batch-mode, ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-03-31 04:44:47.621559
