addons:
  apt: {packages: null}
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 5ee9072e-03e7-4f09-99af-f10e6aad79ac
install: mvn compile org.apache.maven.plugins:maven-dependency-plugin:2.10:go-offline
  --batch-mode --show-version
jdk: [openjdk6]
language: java
script: ['export PATH="bin:$PATH"', mvn clean verify --batch-mode, ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-03-23 08:38:10.536584
