addons:
  apt:
    packages: null
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 389aab25-3ffa-4241-a7aa-ce2d686206d3
after_success:
- ./df-build.sh
install: mvn compile org.apache.maven.plugins:maven-dependency-plugin:2.10:go-offline
  --batch-mode --show-version
jdk:
- openjdk6
language: java
notifications: {}
script:
- export PATH="bin:$PATH"
- mvn clean verify --batch-mode
sudo: false
# Modified by Insights Service at 2016-05-10 16:30:18.005512
