addons:
  apt: {packages: null}
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 201cfad8-ae4a-45fc-94a8-2cabdfbe9afe
install: mvn compile org.apache.maven.plugins:maven-dependency-plugin:2.10:go-offline
  --batch-mode --show-version
jdk: [openjdk6]
language: java
script: ['export PATH="bin:$PATH"', mvn clean verify --batch-mode, ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-04-08 13:22:01.815301
